SELECT month, days FROM (SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-01', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-01', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-02', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-02', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-03', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-03', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-04', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-04', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-05', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-05', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-06', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-06', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-07', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-07', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-08', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-08', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-09', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-09', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-10', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-10', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-11', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-11', '-01'))) as days
    UNION
	 SELECT MONTHNAME(CONCAT(YEAR(CURDATE()), '-12', '-01')) AS month,
			DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-12', '-01'))) as days) as months;